In [28]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import random
%matplotlib inline

In [94]:
np.random.seed(11256964)

In [95]:
my_list = ("electronics", "clothing", "books", "food")
discount =  (0,0.1,0.2)
df = pd.DataFrame({"customer_id": np.random.randint (1,41,200),
                  "category": np.random.choice (my_list,200),
                  "price": np.abs(np.random.normal(50, 15, 200)),
                  "quantity" : np.random.randint (1,6,200),
                  "discount" : np.random.choice (discount,200),
                  "day": np.random.randint (1,31,200)})

In [99]:
print (df)

     customer_id     category      price  quantity  discount  day
0              5        books  63.878192         5       0.1   25
1             33  electronics  35.228955         5       0.0   26
2              4  electronics  39.531719         3       0.0   28
3             18         food  69.267380         3       0.2    9
4             29         food  46.389581         4       0.0   19
..           ...          ...        ...       ...       ...  ...
195           31         food  50.027114         2       0.0   20
196            8         food  19.434906         1       0.0   30
197           32        books  39.730908         1       0.1   13
198           25  electronics  52.480120         4       0.2   10
199           28     clothing  38.114777         3       0.2   23

[200 rows x 6 columns]

In [100]:
#Task 1
df["gross_revenue"]= df["price"] * df["quantity"]
df["net_revenue"] = df["gross_revenue"] * (1 - df["discount"])
print(df["gross_revenue"])
print (df["net_revenue"])

0      319.390959
1      176.144774
2      118.595158
3      207.802140
4      185.558324
          ...
195    100.054228
196     19.434906
197     39.730908
198    209.920479
199    114.344332
Name: gross_revenue, Length: 200, dtype: float64
0      287.451863
1      176.144774
2      118.595158
3      166.241712
4      185.558324
          ...
195    100.054228
196     19.434906
197     35.757817
198    167.936383
199     91.475465
Name: net_revenue, Length: 200, dtype: float64

In [101]:
#Task 2
df["category_avg_net_revenue"] = df.groupby("category")["net_revenue"].transform("mean")

df.head()

,customer_id,category,price,quantity,discount,day,gross_revenue,net_revenue,category_avg_net_revenue
0,5,books,63.878192,5,0.1,25,319.390959,287.451863,140.582804
1,33,electronics,35.228955,5,0.0,26,176.144774,176.144774,138.821239
2,4,electronics,39.531719,3,0.0,28,118.595158,118.595158,138.821239
3,18,food,69.267380,3,0.2,9,207.802140,166.241712,122.155521
4,29,food,46.389581,4,0.0,19,185.558324,185.558324,122.155521

In [111]:
#Task 3
df[(df["net_revenue"] > df["category_avg_net_revenue"])]
df.sample (7)

,customer_id,category,price,quantity,discount,day,gross_revenue,net_revenue,category_avg_net_revenue
107,38,food,57.513330,2,0.0,25,115.026660,115.026660,122.155521
102,18,food,66.865355,5,0.1,29,334.326775,300.894098,122.155521
170,22,clothing,47.058673,4,0.0,11,188.234691,188.234691,143.448865
142,28,clothing,47.394069,4,0.1,24,189.576275,170.618648,143.448865
39,17,books,39.023995,5,0.2,2,195.119977,156.095982,140.582804
186,16,clothing,51.378190,1,0.1,23,51.378190,46.240371,143.448865
146,22,clothing,59.413529,3,0.2,26,178.240588,142.592471,143.448865

In [112]:
df.head(12)

,customer_id,category,price,quantity,discount,day,gross_revenue,net_revenue,category_avg_net_revenue
0,5,books,63.878192,5,0.1,25,319.390959,287.451863,140.582804
1,33,electronics,35.228955,5,0.0,26,176.144774,176.144774,138.821239
2,4,electronics,39.531719,3,0.0,28,118.595158,118.595158,138.821239
3,18,food,69.267380,3,0.2,9,207.802140,166.241712,122.155521
4,29,food,46.389581,4,0.0,19,185.558324,185.558324,122.155521
5,8,clothing,38.025027,1,0.2,18,38.025027,30.420021,143.448865
6,16,food,68.009515,2,0.1,16,136.019029,122.417126,122.155521
7,33,electronics,43.289431,1,0.2,15,43.289431,34.631545,138.821239
8,13,electronics,13.225266,5,0.0,22,66.126329,66.126329,138.821239
9,24,books,51.340283,3,0.0,27,154.020848,154.020848,140.582804
10,8,electronics,33.724688,3,0.0,13,101.174063,101.174063,138.821239
11,15,electronics,39.656325,2,0.1,21,79.312651,71.381385,138.821239

In [125]:
#Task 4
def order_type(row):
    if row["quantity"] >= 4 and row["discount"] > 0:
        return "bulk_discounted"
    elif row["quantity"] >= 4 and row["discount"] == 0:
        return "bulk_fullprice"
    elif row["quantity"] < 4 and row["discount"] > 0:
        return "standard_discounted"
    else:
        return "standard_fullprice"

df["order_type"] = df.apply(order_type, axis=1)

print (df["order_type"])

0          bulk_discounted
1           bulk_fullprice
2       standard_fullprice
3      standard_discounted
4           bulk_fullprice
              ...
195     standard_fullprice
196     standard_fullprice
197    standard_discounted
198        bulk_discounted
199    standard_discounted
Name: order_type, Length: 200, dtype: object

In [126]:
#Task 5
summary_table = df.groupby("category").agg({
    "price": "mean",
    "quantity": "sum",
    "discount": "mean",
    "net_revenue": "sum",
    "customer_id": "count"
})

In [128]:
print (summary_table)

             average_price  total_quantity  average_discount  \
category
books            47.194448             144          0.100000
clothing         52.733259             140          0.113043
electronics      51.198344             165          0.103704
food             50.830402             156          0.115789

             total_net_revenue  number_of_transactions
category
books              6045.060579                      43
clothing           6598.647795                      46
electronics        7496.346899                      54
food               6962.864683                      57